import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const memory = new Map<string,string>();
Object.assign(globalThis, {localStorage: {getItem:(k:string)=>memory.get(k)??null,setItem:(k:string,v:string)=>memory.set(k,v),removeItem:(k:string)=>memory.delete(k)},window:{location:{search:'',protocol:'http:'}}});
let calls=0;
globalThis.fetch = async()=>{calls++; throw Error('Unexpected network');};
const {useNotesStore}=await import('../src/stores/useNotesStore');
const s=()=>useNotesStore.getState();
s().addNote({title:'audit',type:'checklist',color:'yellow',folderId:'work',isPinned:false,isStarred:false,isToday:false,hasReminder:false,isArchived:false,isTrash:false,checklist:[{id:'item',text:'task',completed:false}]});
const note=s().notes.find(n=>n.title==='audit')!; assert.ok(note);
s().toggleChecklistItem(note.id,'item');
assert.equal(s().notes.find(n=>n.id===note.id)!.checklist![0].completed,true);
assert.equal(s().notes.find(n=>n.id===note.id)!.updatedAt,note.updatedAt);
assert.equal(await s().activateCloudSync('invalid'),false); await s().syncFromDB();
assert.ok(s().notes.some(n=>n.id===note.id)); assert.equal(s().cloudSyncEnabled,false);
s().moveToTrash(note.id); s().emptyTrash(); assert.ok(!s().notes.some(n=>n.id===note.id)); assert.equal(calls,0);
const source=fs.readFileSync('electron/main.cjs','utf8');
const handler=source.match(/ipcMain.on\('bubble-move', \(event, \{ deltaX, deltaY \}\) => \{([\s\S]*?)\n  \}\);/)![1];
let position:number[]=[];
const context={bubbleWindow:{isDestroyed:()=>false,getPosition:()=>[100,100],getSize:()=>[150,150],setPosition:(x:number,y:number)=>position=[x,y]},screen:{getDisplayNearestPoint:()=>({workArea:{x:0,y:0,width:1000,height:800}})},deltaX:9999,deltaY:9999};
vm.runInNewContext(`(()=>{${handler}})()`,context); assert.deepEqual(position,[850,650]);
position=[]; context.deltaX=NaN; vm.runInNewContext(`(()=>{${handler}})()`,context); assert.deepEqual(position,[]);
process.env.TZ='Asia/Ho_Chi_Minh';
const RealDate=Date;
(globalThis as any).Date=class extends RealDate {constructor(){super('2026-09-11T17:30:00Z');}};
const {localTodayStr}=await import('../src/lib/dateHelper'); assert.equal(localTodayStr(),'2026-09-12');
globalThis.Date=RealDate;
console.log('PASS: actual store CRUD/checklist/no-network containment, IPC bounds/NaN, local date +07 midnight');
